### ISSUE TITLE
FEAT: Business styles

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#10]
### What feature?

- [x] Add colors
- [x] Add typography 

Doc: https://chakra-ui-git-fix-typescript-autocomplete.chakra-ui.vercel.app/docs/theming/theme

### Add screenshots

![image](https://github.com/user-attachments/assets/1e21f2cf-d566-4f3f-9271-2f15968e5748)

**Comment by DaniellaZambrano** [comment]
@XCODE89 Can you please include the hex code of the color you use next to the image? Also, for the typography, could you provide the name and the source where it was obtained from? Thanks :)

**Comment by DaniellaZambrano** [comment]
thanks for your help. Already the file was in the correspond CSS file :)
