### ISSUE TITLE
TASK: Update HttpMethod usage

### ISSUE THREAD

**Issue by sofiia-trokhymchuk** [BinaryStudioAcademy/bsa-2024-outreachvids#100]
- [x] Update specifying HttpMethod from string to [HttpMethod enum](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/blob/next/shared/src/framework/http/enums/http-method.enum.ts) values

**Comment by DaniellaZambrano** [comment]
Clarity and maintainability

**Comment by DaniellaZambrano** [comment]
It overlaps the Play button when is in Portrait mode 

![Image](https://github.com/user-attachments/assets/3d9dc8ad-8e51-43d7-b5f7-ee88d66e7a5c)
