### ISSUE TITLE
FEAT: Add video items menu to studio page

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#101]
### What feature?

Add video items menu to studio page

### Add screenshots

<img width="1007" alt="Screenshot 2024-08-30 at 16 09 11" src="https://github.com/user-attachments/assets/c2b2152d-65ce-4e19-8151-9cfcaa17c1d4">

**Comment by alien513** [comment]
The component works as expected.

![Image](https://github.com/user-attachments/assets/d7bcc060-c4bf-4b07-9fc5-08765c15b334)
