### ISSUE TITLE
FEAT: Add avatars menu

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#102]
### What feature?

Add avatars menu body view.

### Add screenshots

![Image](https://github.com/user-attachments/assets/6ca052bb-feee-412e-9bbc-6c629ec1d5d2)

**Comment by alien513** [comment]
The component works correctly.

![Image](https://github.com/user-attachments/assets/f0c40268-c7d3-4ea6-915b-6f5707f13f6e)
