### ISSUE TITLE
FEAT: Add scripts menu

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#104]
### What feature?

Add scripts menu body view.

### Add screenshots

<img width="335" alt="Screenshot 2024-08-30 at 16 54 49" src="https://github.com/user-attachments/assets/80169f74-e7e7-4d56-a991-d84b0759b181">

**Comment by o-nedashkivska** [comment]
Waiting for decision on styles

**Comment by alien513** [comment]
Script panel should contain the Script Text Area: A text box containing the current script: "Welcome to the new era of video creation with App! Simply type your script to get started!"

![Image](https://github.com/user-attachments/assets/4b0231c3-d4fa-436e-ac39-afc80c14a881)

**Comment by o-nedashkivska** [comment]
For now by default we will not have any scripts. Maybe, we will change it in future PRs when we decide on app flow.

**Comment by alien513** [comment]
Thanks for clarifying. Removing the corresponding acceptance criterion as of now.
