### ISSUE TITLE
FEAT: Add avatars endpoint

### ISSUE THREAD

**Issue by WilsonBravo** [BinaryStudioAcademy/bsa-2024-outreachvids#105]
## What feature?
Add avatars enpoint.

- [x] create database diagram for storing avatar information
- [x] implement avatar service methods to interact with avatar information
- [x] create controller
- [x] create enpoint

**Comment by DaniellaZambrano** [comment]
database diagram for storing avatar information is not created 


![Image](https://github.com/user-attachments/assets/e694df9c-07b1-4232-9b16-d605cad772c8)

Steps to reproduce:

1. Do a `git pull` to have all up to date
2. run `npm install`
3. run `npm run migrate:dev -w backend`
4. The DB creates new tables but not the table for storing avatar information

**Comment by DaniellaZambrano** [comment]
A new ticket was created to this.

https://github.com/orgs/BinaryStudioAcademy/projects/30/views/1?sliceBy%5Bvalue%5D=DaniellaZambrano&pane=issue&itemId=79189772
