### ISSUE TITLE
FEAT: Header component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#11]
### What feature?

- [x] Add header component

Doc: https://v2.chakra-ui.com/docs/components

### Add screenshots

![image](https://github.com/user-attachments/assets/d9da1e5f-66cf-4ac1-b318-3b32cdf161d1)

**Comment by alien513** [comment]
Updated header component works as expected.

![Image](https://github.com/user-attachments/assets/7822b581-eb79-47d9-a164-49810cbed35d)
