### ISSUE TITLE
FEAT: Add timeline component to studio page

### ISSUE THREAD

**Issue by Alblupynos** [BinaryStudioAcademy/bsa-2024-outreachvids#110]
### What feature?

Add timeline component to studio page.

### Add screenshots

![Image](https://github.com/user-attachments/assets/b6fa7b7e-5107-4bc9-9de0-6ca6d5ea6cce)

### Acceptance criteria

The timeline component is visible on the studio page.

**Comment by Sanchousina** [comment]
Please attach pr to the issue

**Comment by alien513** [comment]
The timeline component was added to the Studio page.

![Image](https://github.com/user-attachments/assets/fa312840-e549-4a90-9616-93d2ff9cd20d)
