### ISSUE TITLE
FEAT: Update protected Route

### ISSUE THREAD

**Issue by XCODE89** [BinaryStudioAcademy/bsa-2024-outreachvids#114]
What task?
Get the user from the store to access protected routes.

**Comment by nikita-remeslov** [comment]
@XCODE89 please update the task to our standard!

**Comment by alien513** [comment]
Could you please provide more information about the task?

**Comment by alien513** [comment]
Thanks for explaining everything in Slack. The component works as expected.
![Image](https://github.com/user-attachments/assets/de6f9abd-56ac-4590-871f-7ab36c925de3)
![Image](https://github.com/user-attachments/assets/c590360a-38b5-4eea-a649-78ccef90976f)
