### ISSUE TITLE
FEAT: User card

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#12]
### What feature?

- [x] Add user card

Doc: https://v2.chakra-ui.com/docs/components

### Add screenshots

![image](https://github.com/user-attachments/assets/f034e5ba-3878-4ca6-88dd-d1aa111734e0)

**Comment by alien513** [comment]
Waiting for the Sidebar component implementation

**Comment by alien513** [comment]
The component works correctly.

![Image](https://github.com/user-attachments/assets/aec83cf0-4885-4f80-a6bf-9931341546a7)
