### ISSUE TITLE
FEAT: Sidebar component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#13]
### What feature?

- [x] Add sidebar
- [x] Sidebar should have collapsed styles
- [x] By default sidebar should be expanded
- [x] Log out button should log out the user

Doc: https://v2.chakra-ui.com/docs/components

### Add screenshots

![image](https://github.com/user-attachments/assets/75210c7e-7c35-4ad4-a5a0-e60f6cde689d)

**Comment by DaniellaZambrano** [comment]
How can I see this component?

**Comment by JKaypa** [comment]
You can place it in a new or already created page to render it

**Comment by DaniellaZambrano** [comment]
Perfect thanks

![Image](https://github.com/user-attachments/assets/871b8f73-ae19-4165-a49d-bbda86f6bc6f)

**Comment by DaniellaZambrano** [comment]
I think for a new ticket maybe that on smaller screens, the sidebar may default to collapsed mode
