### ISSUE TITLE
FEAT: Add script to timeline component

### ISSUE THREAD

**Issue by Alblupynos** [BinaryStudioAcademy/bsa-2024-outreachvids#138]
### What feature?

Add script text to the timeline after the plus button is clicked.

### Add screenshots

![Image](https://github.com/user-attachments/assets/2f3b4ae3-02b2-487c-a581-4adbad17dc38)

### Acceptance criteria

The script text is visible on the timeline component.

**Comment by Alblupynos** [comment]
Hi, that was done in another task, if I'm correct @o-nedashkivska did this. Maybe create a bug ticket to fix this.

**Comment by o-nedashkivska** [comment]
This is not a suggestion, this is default script text. When user focuses it he can edit it.

**Comment by DaniellaZambrano** [comment]
Ok so if is the default script, it's ok. Thank you Albina and Oleksandra!
