### ISSUE TITLE
FEAT: Open modal video on create video click

### ISSUE THREAD

**Issue by stefano-lacorazza** [BinaryStudioAcademy/bsa-2024-outreachvids#139]
When clicking create video on the sidebar, a new video modal should appear.

**Comment by stefano-lacorazza** [comment]
https://github.com/user-attachments/assets/246c4ecd-5eec-4888-8244-3b3b64fc9761

**Comment by DaniellaZambrano** [comment]
Thank you Stefano, also you used the implemented [component](https://github.com/orgs/BinaryStudioAcademy/projects/30/views/1?filterQuery=is%3Aissue+assignee%3Asergiy4&pane=issue&itemId=75383600) perfect!

![Image](https://github.com/user-attachments/assets/e6ac21e6-6258-4a64-84bc-1f43a8588de9)
