### ISSUE TITLE
Update HttpMethods to use enum insted of plain string

### ISSUE THREAD

**Issue by lfelix3011** [BinaryStudioAcademy/bsa-2024-outreachvids#141]
This task is to Update the http methods that was add before the merge of this task: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/100

**Comment by alien513** [comment]
The code was updated as required.

![Image](https://github.com/user-attachments/assets/7a83b594-e601-4e4c-8e73-f1f45d7c213a)
