### ISSUE TITLE
FEAT: Add player controls to studio page

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#142]
### What feature?

Add player controls to the studio page above the timeline element

**Comment by Sanchousina** [comment]
Blocked because of not valid diff. Waiting for OV-110 to be merged

**Comment by DaniellaZambrano** [comment]
OV-110 already merged and AC passed 

![Image](https://github.com/user-attachments/assets/6f3a1244-1850-444b-b6c0-fe402c662d30)
