### ISSUE TITLE
FEAT: Add create avatar page

### ISSUE THREAD

**Issue by WilsonBravo** [BinaryStudioAcademy/bsa-2024-outreachvids#147]
### What feature?

- [x] Add create avatar route
- [x] Add instruction component

### Add screenshots

![Image](https://github.com/user-attachments/assets/2ad564a6-264c-4056-81f3-6da495568a45)

**Comment by stefano-lacorazza** [comment]
Created new pull request https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/203 based on https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/tree/task/OV-164-Remove-sx-prop to remove sx props and update protected routing.
