### ISSUE TITLE
TASK: Create test documentation for BE Implementation Tickets

### ISSUE THREAD

**Issue by DaniellaZambrano** [BinaryStudioAcademy/bsa-2024-outreachvids#149]
### What task?

- How to review the codebase

The link to the doc:
https://docs.google.com/document/d/1kLCrCMu5tNskydQBHya0pXj9FiVzXrX0JzwuyChyr70/edit?usp=sharing

**Comment by alien513** [comment]
Perhaps, Pass/Fail criteria should be treated as Acceptance criteria and formalized accordingly? Maybe, it's better to rewrite it in a Check list/Test cases format, so that it is clear what testing artifact it is?

**Comment by DaniellaZambrano** [comment]
Oh The acceptance criteria are in the ticket they come from. I didn’t want to make it redundant, but I’ll check
