### ISSUE TITLE
FEAT: Fetch avatars and show them in video-menu

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#153]
### What feature?

Fetch avatars and show them in video-menu

**Comment by o-nedashkivska** [comment]
Depends on [Add scripts menu](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/104) and [Add avatars endpoint](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/105)

**Comment by DaniellaZambrano** [comment]
I'm blocked with this because the [Add avatars endpoint](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/105) have an issue

**Comment by DaniellaZambrano** [comment]
Responded on Slack. Thanks!
