### ISSUE TITLE
TASK: Change time starting point in timeline component

### ISSUE THREAD

**Issue by Alblupynos** [BinaryStudioAcademy/bsa-2024-outreachvids#154]
### What task?

The time starting point must be 00:00.

### Add screenshots

![Image](https://github.com/user-attachments/assets/dba2a10b-79e1-40e5-b0d8-ff9fb2b7682b)

**Comment by Alblupynos** [comment]
> I saw a 0 I don't think that should appear
> 
> ![Image](https://github.com/user-attachments/assets/6ab97e97-43e4-4e28-abef-fe52b3c88397)

I'm not sure where it is coming from, but I checked the current dev branch that will be merged soon and it does not reproduce. 


![Image](https://github.com/user-attachments/assets/fd3f60a0-9d01-4f61-8fed-13076371ed0a)

**Comment by DaniellaZambrano** [comment]
Mmm ok, on `next` it is still reproducing, so I'm goint to wait :)

**Comment by DaniellaZambrano** [comment]
Checked Albina, thanks!
