### ISSUE TITLE
FEAT: Add logic for the resize button

### ISSUE THREAD

**Issue by sergiy4** [BinaryStudioAcademy/bsa-2024-outreachvids#157]
### What feature?

You should add logic for the resize button

**Comment by DaniellaZambrano** [comment]
It overlaps the Play button when is in Portrait mode

![Image](https://github.com/user-attachments/assets/4983e941-7d3e-4fe0-a807-0db8bfb60df1)

**Comment by DaniellaZambrano** [comment]
another example with dimensions
![Image](https://github.com/user-attachments/assets/5bc9133c-384e-4ba2-beae-c205dbb3ca36)

**Comment by sergiy4** [comment]
Here is the ticket that resolves the styling issue and is awaiting review. https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/197

**Comment by DaniellaZambrano** [comment]
ok so waiting

**Comment by DaniellaZambrano** [comment]
This [ticket ](https://github.com/orgs/BinaryStudioAcademy/projects/30/views/6?sliceBy%5Bvalue%5D=DaniellaZambrano&filterQuery=is%3Aissue+label%3AQA+assignee%3ASanchousina&pane=issue&itemId=78940752) resolves the styling issue
