### ISSUE TITLE
FEAT: Integrate Azure AI

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#16]
### What feature?

Integrate Azure AI into our application.

Create a service class on the backend where you should develop 2 methods:

1. Get the avatar from azure sdk
2. Transform text to speech

Create a controller and a service where we can call the Azure class

Useful links:

Tutorial how to do it In React: https://raokarthik83.medium.com/building-a-text-to-speech-avatar-app-with-reactjs-and-azure-tts-avatar-ai-c9d2da0e9f75
https://learn.microsoft.com/uk-ua/javascript/api/microsoft-cognitiveservices-speech-sdk/avatarconfig?view=azure-node-latest
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech-avatar/avatar-gestures-with-ssml

**Comment by o-nedashkivska** [comment]
Splitted into two tasks:

1. Add Azure integration for voices and text to speech https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/172
2. Add Azure integration for avatars https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/173

**Comment by Sanchousina** [comment]
Do we still need this ticket?

**Comment by o-nedashkivska** [comment]
I will close it when all related tickets will be merged.

**Comment by o-nedashkivska** [comment]
Splitted into two tasks:

Add Azure integration for voices and text to speech https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/172
Add Azure integration for avatars https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/173
