### ISSUE TITLE
FEAT: Add avatar to timeline item

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#165]
### What feature?

When a user clicks on timeline item with type 'Avatar' and then selects avatar from the video menu, the selected avatar must appear in the timeline item

**Comment by DaniellaZambrano** [comment]
Does this ticket depend on another one? According to the description, I reproduce it, but it doesn’t happen

**Comment by o-nedashkivska** [comment]
No, it does not depend on any other tasks because it is merged already. Did you try to repeat actions like in the video? https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/200

**Comment by DaniellaZambrano** [comment]
Thanks for your response! Yes now it works :D
