### ISSUE TITLE
FEAT: Add AI icon to scripts menu

### ISSUE THREAD

**Issue by WilsonBravo** [BinaryStudioAcademy/bsa-2024-outreachvids#166]
### What feature?

- [x] Add AI icon button to scripts menu
- [x] Open chat component when button is pressed

### Add screenshots

![Image](https://github.com/user-attachments/assets/eebec8db-cb8e-48af-8de9-a0b113fdf67c)

**Comment by alien513** [comment]
The functionality was added.

![Image](https://github.com/user-attachments/assets/7118e4e2-2fe1-417c-93ff-f1502f235a2c)
