### ISSUE TITLE
TASK: Sign in flow (backend) testing documentation

### ISSUE THREAD

**Issue by alien513** [BinaryStudioAcademy/bsa-2024-outreachvids#168]
### What task?

- [x] Create the check list
- [x] Create test cases

### Testing Documentation

https://docs.google.com/spreadsheets/d/14vF3EOa7sI515qRntANlLpbEsZBukRq-S1vcsAIy_wg/edit?gid=1927397104#gid=1927397104

**Comment by alien513** [comment]
https://docs.google.com/spreadsheets/d/14vF3EOa7sI515qRntANlLpbEsZBukRq-S1vcsAIy_wg/edit?gid=1927397104#gid=1927397104

**Comment by DaniellaZambrano** [comment]
Perfect
