### ISSUE TITLE
BUG: AWS build fails

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#174]
### Describe your issue

AWS build fails, the error:

![Image](https://github.com/user-attachments/assets/32725e4c-50ea-4ace-a4ab-8b6230d72afb)

### Steps to reproduce

1. Go to http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com/

### What was the actual result?

![Image](https://github.com/user-attachments/assets/d7cbd0f4-d1f7-4b0b-9669-41002e8dbc73)

### What was the expected result?

App works as before

### Put here any screenshots or videos (optional)

The bug appeared after pr https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/118

### What OS are you seeing the problem on?

Other (mention in the description)

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Blocker (S1)

**Comment by alien513** [comment]
The bug was fixed.
