### ISSUE TITLE
FEAT: Add create video modal

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#18]
### What feature?

- [x] Add create video modal use chakra ui
- [x] Add button for landscape view 1920x1080
- [x] Add button for portrait view 1080x1920
- [x] Button hover should change the preview

P.S. Reference https://heygen.com

### Add screenshots

![Image](https://github.com/user-attachments/assets/bdcd6cff-8a12-4753-828e-920ef6cc69a4)

**Comment by DaniellaZambrano** [comment]
This works as expected from the frontend, as seen in the image

**Comment by DaniellaZambrano** [comment]
This works as expected from the frontend, as shown in the image.

**Comment by DaniellaZambrano** [comment]
![Image](https://github.com/user-attachments/assets/b15099d6-5973-49f0-8f29-3e1864ec1968)
