### ISSUE TITLE
TASK: Set lower priority to Chakra styles

### ISSUE THREAD

**Issue by Alblupynos** [BinaryStudioAcademy/bsa-2024-outreachvids#180]
### What task?

Make Chakra load before module CSS styles.
https://stackoverflow.com/questions/73073413/how-to-override-chakra-ui-or-emotion-css-in-js-styling-with-normal-css-class-n

**Comment by DaniellaZambrano** [comment]
According to the inspector, the Chakra styles are being loaded first. Passed!
![Image](https://github.com/user-attachments/assets/ddc3ed01-2c26-44a1-99de-032d62046fdf)
