### ISSUE TITLE
BUG: Fix crypto error on deployed app

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#182]
### Describe your issue

crypto does not work on deployed app

### Steps to reproduce

1. Go to http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com/

### What was the actual result?

![Image](https://github.com/user-attachments/assets/e8f9d070-4f57-420f-9ed1-5f6114f87e20)

### What was the expected result?

App works as before

### What OS are you seeing the problem on?

Other (mention in the description)

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Blocker (S1)

**Comment by DaniellaZambrano** [comment]
Perfect, thank you so much :)

**Comment by DaniellaZambrano** [comment]
![Image](https://github.com/user-attachments/assets/5bc584b3-c4f4-4350-b475-875c522716f5)
