### ISSUE TITLE
BUG: Error messages from backend are unclear, contain unnecessary tech details and non-English text

### ISSUE THREAD

**Issue by alien513** [BinaryStudioAcademy/bsa-2024-outreachvids#184]
### Describe your issue

Some error messages from backend are unclear, contain unnecessary tech details and non-English text

### Steps to reproduce

**In the browser:**

**Option 1: Email length issue**
1. Open the page http://localhost:3000/sign-up.
2. In the Full Name field enter the valid full name, for example Olena Test.
3. In the Email field enter the email, which is > 255 ot <= 320 characters long, for example [olenaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com](mailto:olenaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com).
4. In the Password field enter the valid password, for example 123456.
5. In the Repeat Password field repeat the password, for example 123456.
6. Press the Sign Up button.

**Option 2: Duplicate user issue**
1. Open the page http://localhost:3000/sign-up.
2. In the Full Name field enter the valid full name, for example Olena Test.
3. In the Email field enter the valid email, for example: olena@gmail.com.
4. In the Password field enter the valid password, for example 123456.
5. In the Repeat Password field repeat the password, for example 123456.
6. Press the Sign Up button.
7. Click Log Out.
8. Open the page http://localhost:3000/sign-up.
9. In the Full Name field enter the valid full name, for example Olena Test.
10. In the Email field enter the valid email, for example: olena@gmail.com.
11. In the Password field enter the valid password, for example 123456.
12. In the Repeat Password field repeat the password, for example 123456.
13. Press the Sign Up button.

### What was the actual result?

Both options: The user gets an error message which is not clear and contains unnecessary technical details, please check the screenshots.

### What was the expected result?

Option 1: The user gets a standard user-friendly error message, e. g. "Please  enter a valid email."
Option 2: The user gets a standard user-friendly error message, e. g. "This user already exists."

### Put here any screenshots or videos (optional)

Option 1:

![Image](https://github.com/user-attachments/assets/72b51b18-e7ae-4bfa-b20f-fccb93ba4729)

Option 2 (created by Wilson Bravo):

![Image](https://github.com/user-attachments/assets/65163c7a-8cb3-4475-a0b2-d5e4eae5aace)

### What OS are you seeing the problem on?

Windows 11

### What browsers are you seeing the problem on?

Firefox 129.0.2 (64x)
Chrome 128.0.6613.113 (x64)

### Severity

Minor (S4)

**Comment by stefano-lacorazza** [comment]
This error occurred because, when the users table was created, no maximum length was specified for the email field. Consequently, the database defaulted to a maximum length of 255 characters. The application validations, however, expected a maximum length of 320 characters. As a result, if an email length was between 255 and 320 characters, the validation did not throw an error, but the database did when attempting to create the new user. This resulted in the technical error message.
Fixed with https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/342

**Comment by alien513** [comment]
The bug was fixed.
