### ISSUE TITLE
FEAT: Fix sign in redirection after logout

### ISSUE THREAD

**Issue by JKaypa** [BinaryStudioAcademy/bsa-2024-outreachvids#187]
### What feature?

Fix logout redirection to sign in

### Acceptance criteria

- [ ] Ensure that the system displays appropriate error messages when unauthorized users attempt to access protected routes
- [ ] Verify that logging out a user revokes their tokens
- [ ] Verify that logging out a user redirects them to Sign In page

### Testing documentation

https://docs.google.com/spreadsheets/d/1Dn7B49WQK0oi5bE3dmx_Ay1TH0Y1p3QUNDn3VvKWH0o/edit?gid=1927397104#gid=1927397104

**Comment by alien513** [comment]
Hi! I understand that this ticket is in Peer Review, but there's a bug related to it: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/210

**Comment by alien513** [comment]
And one more bug here: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/213

**Comment by JKaypa** [comment]
Those bugs are fixed with this PR

**Comment by alien513** [comment]
Log Out redirection has been fixed. All bugs resolved.
