### ISSUE TITLE
BUG: Unexpected label "Loading..." is displayed when site pages are loading

### ISSUE THREAD

**Issue by alien513** [BinaryStudioAcademy/bsa-2024-outreachvids#188]
### Describe your issue

When site pages load, we can observe the label "Loading..." in the upper left corner, which is not supposed to be there by design.

### Steps to reproduce

1. Open the deployed site: http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com/sign-in.
2. Check the upper left corner of the screen.

### What was the actual result?

When the page is opened, the label "Loading..." is displayed.

### What was the expected result?

The special loader component should be displayed.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/3a52a675-ee4b-488e-a385-5ff9fd5ab644)

### What OS are you seeing the problem on?

Windows 11

### What browsers are you seeing the problem on?

Firefox 129.0.2 (64x)
Chrome 128.0.6613.113 (x64)

### Severity

Minor (S4)

**Comment by o-nedashkivska** [comment]
Must be solved now

**Comment by alien513** [comment]
Bug was fixed.
