### ISSUE TITLE
FEAT: Add loader to auth page

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#189]
### What feature?

Replace loader mock to valid loader in auth page. Make sure to wrap it in Overlay component.

### Add screenshots

![Image](https://github.com/user-attachments/assets/f05a2611-8010-473a-b29a-83ce87c2ffee)

**Comment by alien513** [comment]
Valid loader is displayed.

![Image](https://github.com/user-attachments/assets/be2c15ba-7d4f-4282-bd0f-ab6aeb0f878c)
