### ISSUE TITLE
BUG: Fix styling in studio page

### ISSUE THREAD

**Issue by DaniellaZambrano** [BinaryStudioAcademy/bsa-2024-outreachvids#194]
### Describe your issue

-

### Steps to reproduce

1

### What was the actual result?

1

### What was the expected result?

-

### What OS are you seeing the problem on?

Windows, MacOS

### What browsers are you seeing the problem on?

Chrome, Safari, Edge, Firefox, Opera

### Severity

Minor (S4)

**Comment by DaniellaZambrano** [comment]
@Sanchousina can you give me more details about the fixing please?

**Comment by Sanchousina** [comment]
> @Sanchousina can you give me more details about the fixing please?

What details do you need besides those I provided in my pr comment?

**Comment by DaniellaZambrano** [comment]
Thank you, yes I noticed that
