### ISSUE TITLE
FEAT: Sign-in flow

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#2]
### What feature?

- [x]  Update service to get user
- [x]  Update encryption service to compare user password with the hash
- [x]  Add /auth/sign-in endpoint to the controller
- [x]  Return object with user property in response (exclude password_hash and password_salt columns)
- [x]  Add validation (check with the dev who is implementing FE task)

**Comment by alien513** [comment]
Added acceptance criteria.
Component works as expected.
