### ISSUE TITLE
FEAT: Add play button to scripts on video-menu

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#202]
### What feature?

Add play button to scripts on video-menu and make it play mocked audio.

### Add screenshots

![Image](https://github.com/user-attachments/assets/fe45ff8a-eb01-446e-9386-500c729ef459)

**Comment by alien513** [comment]
Play icon was added.

![Image](https://github.com/user-attachments/assets/e555d7ba-f1ed-426f-92d4-81e491806f9b)
