### ISSUE TITLE
FEAT: Add voices modal

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#205]
### What feature?

Add voices modal with list of voices (mock data for now). Add gender info to the voice card.

Reuse video modal created in [this pr](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/36) if possible.

Use HeyGen as a reference but apply our app colors.

### Add screenshots

![Image](https://github.com/user-attachments/assets/8a3a60a5-f065-45a7-b3e0-6dad8097ce67)

**Comment by alien513** [comment]
Voices modal (mock data for now) was added.

![Image](https://github.com/user-attachments/assets/d510cb87-6282-4658-b40f-091d34c49b64)
