### ISSUE TITLE
FEAT: Change download button to submit button on studio page

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#206]
### What feature?

Change download button to submit button on studio page. When user clicks on this button redirect to homepage.

### Add screenshots

![Image](https://github.com/user-attachments/assets/71c35ec9-fd03-452a-b4a4-7d86283e5ae3)

**Comment by alien513** [comment]
The component works as expected.

![Image](https://github.com/user-attachments/assets/4680fb44-f61f-4629-9a9f-8b1017fc285e)
