### ISSUE TITLE
FEAT: Redirect to home page on logo click

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#207]
### What feature?

When user clicks on logo on the studio page redirect to home page.

### Add screenshots

![Image](https://github.com/user-attachments/assets/2d420f1e-df70-41c5-94f8-e702ccd435e2)

**Comment by DaniellaZambrano** [comment]
It works

![Image](https://github.com/user-attachments/assets/ea2c9bed-136c-41d2-9386-3fe47868f5fd)
