### ISSUE TITLE
FEAT: Add scripts and avatars from timeline

### ISSUE THREAD

**Issue by Alblupynos** [BinaryStudioAcademy/bsa-2024-outreachvids#212]
### What feature?

Add an empty script when pressing the plus button on the timeline. Depends on https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/198

**Comment by DaniellaZambrano** [comment]
Working
![Image](https://github.com/user-attachments/assets/532cac66-c67e-4c85-8846-ed2e91c48d07)
