### ISSUE TITLE
FEAT: Open studio page

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#219]
### What feature?

- On click on the 'use landscape' or 'use portrait' buttons - open the studio page
- Store video size in studio slice

### Add screenshots

![Image](https://github.com/user-attachments/assets/5bd283d5-d4a9-4c60-9624-d226817832ef)

**Comment by o-nedashkivska** [comment]
Please, attach PR

**Comment by alien513** [comment]
The component works as expected.
