### ISSUE TITLE
TASK: Create a test strategy

### ISSUE THREAD

**Issue by SerhijNazarchuk** [BinaryStudioAcademy/bsa-2024-outreachvids#23]
### What task?

Create a test strategy of Outreachvids to define the general approach that should be used during software testing and when evaluating the results of this testing. Work on the task is carried out in pairs, as a result, a ready-made document in the Google Spreadsheets format should be created

Docs File: https://docs.google.com/document/d/1ZI1qRvsOcsClYgvn6qEthy59eB4v2PYFFEGKxhQwkIM/edit?usp=drive_link

**Comment by alien513** [comment]
Daniella Zambrano: Create the test strategy
Olena Kapustina (alien513): Review the test strategy, make suggestions

**Comment by DaniellaZambrano** [comment]
- [ ] Daniella did the first fill of the template with basic knowledge.
- [ ] Daniella is asking in the dev and coach groups to gather more information and confirm the requirements.
- [ ] Daniella reviews the grammar and ensures that the document is clear.
- [ ] Daniella shares the document with Elena for her review to get a fresh perspective

**Comment by DaniellaZambrano** [comment]
- [ ] Elena reviews the document, providing suggestions and annotations for improvement.
- [ ] Elena assists in formatting the document and offers suggestions to enhance clarity.
- [ ] Elena resends the document to Daniella for further review.

**Comment by DaniellaZambrano** [comment]
- [ ] Daniella incorporates Elena's feedback.
- [ ] Daniella implements Elena's suggestions and makes the necessary corrections to the document.
