### ISSUE TITLE
FEAT: Add endpoint to get videos by user id

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#233]
### What feature?

Add endpoint to get videos by user id to Video controller

**Comment by DaniellaZambrano** [comment]
I followed the steps you did but the response is different for me.

see:

1. I signed in obtaining the user_id corresponding. Also I saved the token

 ![Image](https://github.com/user-attachments/assets/c7222e6a-0521-4d01-9316-75d298f2b0bd)

2. I send a request with the user_id but the response is not correct (auth: my_token)

![Image](https://github.com/user-attachments/assets/5d581b53-c151-47c0-9b75-1b9c7dfe12fa)

3. Tested with only endpoint `videos` and it's working

![Image](https://github.com/user-attachments/assets/b9dcffa3-eaba-40b4-b0f4-f693e378b412)

**Comment by alien513** [comment]
I confirm that I get the same results as Daliella.
