### ISSUE TITLE
TASK: Create a mind map

### ISSUE THREAD

**Issue by SerhijNazarchuk** [BinaryStudioAcademy/bsa-2024-outreachvids#24]
### What task?

Create a mind map to visualize the application's work, and user flows while taking into account different user roles. Work on the document is conducted in pairs. As a result, a document should be created on Google Drive

### Add screenshots

![Image](https://github.com/user-attachments/assets/2e67df8d-2fea-4e58-ab0b-bfd2c57c4f9d)

**Comment by alien513** [comment]
Olena Kapustina (alien513): Create the mind map
Daniella Zambrano: Review the mind map, make suggestions

**Comment by alien513** [comment]
- [ ] Elena created the mind map.
- [ ] Elena shared the mind map with the team for suggestions.

**Comment by alien513** [comment]
- [ ] Daniella reviewed the map and shared her observations.

**Comment by alien513** [comment]
- [ ] Elena implemented Daniella's and team suggestions and made the necessary corrections to the map.
