### ISSUE TITLE
FEAT: Add download button to video

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#250]
### What feature?

Add download button to video context menu on the home page.

### Add screenshots

![Image](https://github.com/user-attachments/assets/b7780abf-18e4-4627-a2cb-ea5744fbe951)

### Acceptance criteria

- [ ] 'Download' option should be added to the video menu.
- [x] Clicking the button should result in downloading the video.

**Comment by alien513** [comment]
Component works as expected.

![Image](https://github.com/user-attachments/assets/108659b5-c05c-45f4-a631-af1f97e58f25)
