### ISSUE TITLE
BUG: Refreshing page several times causes UI/Content to not load properly

### ISSUE THREAD

**Issue by DaniellaZambrano** [BinaryStudioAcademy/bsa-2024-outreachvids#261]
### Describe your issue

When the user refreshes the page multiple times, an error message appears

### Steps to reproduce

1. Go to home page (already login)
2. Refresh the page using the browser's refresh button or Ctrl + R.
3. The page refresh in /sign-in (clearing the auth data) 
4. Refresh the page using the browser's refresh button or Ctrl + R.
5. The redirects show an error message

### What was the actual result?

![Image](https://github.com/user-attachments/assets/713463df-e687-466d-a935-e29910e43243)

### What was the expected result?

After refresh a page, still in the same page 

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome, Safari, Edge, Firefox, Opera

### Severity

Critical (S2)

**Comment by o-nedashkivska** [comment]
Should be fixed now
