### ISSUE TITLE
FEAT: Add studio page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#27]
### What feature?

- [x] Add route for Studio page /studio
- [x] Add header to the page (we can reuse out Home page header with some updates)

### Add screenshots

![Image](https://github.com/user-attachments/assets/b24eb126-d305-475a-b627-6899a9546009)

**Comment by DaniellaZambrano** [comment]
Steps to reproduce: (Browser Microsoft Edge Version 128.0.2739.42)
1. Go to the http://localhost:3000/studio
2. You can see the header to the page

![Image](https://github.com/user-attachments/assets/e53f03d2-733b-4e7d-9696-dd0e835d7de0)

**Comment by DaniellaZambrano** [comment]
Acceptance criteria passed!
