### ISSUE TITLE
FEAT: Update logo and loader

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#272]
### What feature?

Find all places where we need logo and replace it with valid logo from figma

### Add screenshots

![Image](https://github.com/user-attachments/assets/0d1310bd-85be-4daa-9e61-d6626c3ef447)

**Comment by DaniellaZambrano** [comment]
Report bug in [this ticket](https://github.com/orgs/BinaryStudioAcademy/projects/30/views/1?pane=issue&itemId=79659834)
