### ISSUE TITLE
FEAT: Add Remotion player

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#28]
### What feature?

- [x] Add Player component to render remotion video
- [x] Player should apply different sizes ( 1920x1080, 1080x1920)
- [x] We can change player size using Resize button in the header

Lib: https://www.remotion.dev/docs/player/ 

### Add screenshots

![Image](https://github.com/user-attachments/assets/89c6e2ac-e156-4e75-bb22-554800e5dc2f)

**Comment by DaniellaZambrano** [comment]
@WilsonBravo I need more information to test it :)
