### ISSUE TITLE
BUG: Modal Close Button Not Accessible on Mobile Devices

### ISSUE THREAD

**Issue by DaniellaZambrano** [BinaryStudioAcademy/bsa-2024-outreachvids#288]
### Describe your issue

The modal can only be closed by clicking the "X" button, which is not visible on some mobile devices, this makes it impossible to close the modal, as there is no alternative method, like clicking outside the modal or another visible close option.

### Steps to reproduce

1. Open the application on a mobile device or emulate a mobile view on a desktop browser.
2. Trigger the modal to appear.
3. Try to close the modal by locating the "X" button.
4. Observe that on mobile devices, the "X" button is not visible, and there is no other way to close the modal.

### What was the actual result?

![Image](https://github.com/user-attachments/assets/dd8630bf-8556-49e7-8869-77c47fce553e)

### What was the expected result?

Users should be able to close the modal either by:

- Clicking a clearly visible "X" button on all device types and screen sizes, or
- Clicking outside the modal to close it.

### What OS are you seeing the problem on?

Other (mention in the description)

### What browsers are you seeing the problem on?

Other (mention in the description)

### Severity

Critical (S2)

**Comment by o-nedashkivska** [comment]
We are not going to support studio page for mobile devices.
