### ISSUE TITLE
FEAT: Add video items menu

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#29]
### What feature?

- [x] Add a menu that can apply any type of body as a child
- [x] After you click on menu icon, menu body should open
- [x] Menu body should apply child and title as a props

### Add screenshots

![Image](https://github.com/user-attachments/assets/78d13901-d80f-430c-b334-d8e615a84d52)

**Comment by alien513** [comment]
The component works correctly. Detailed documentation will be added as a part of Studio page testing.

![Image](https://github.com/user-attachments/assets/1ee2bbd6-e4a5-4403-a61c-e1e2c3dd9347)
