### ISSUE TITLE
FEAT: Add video ending cursor

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#294]
### What feature?

Add video ending cursor. It should be placed after the last script on the timeline

### Add screenshots

![Image](https://github.com/user-attachments/assets/9e596c7b-0fdc-49a6-9e38-08b9996e9001)

**Comment by DaniellaZambrano** [comment]
Is the video ending when the person stops talking? Because if you watch it, the video ends much earlier than the indicated `end`

https://github.com/user-attachments/assets/a4356705-6a97-4072-83a1-f9e7b8b7e797

**Comment by DaniellaZambrano** [comment]
Sometimes it does get fixed, but sometimes it doesn't

![Image](https://github.com/user-attachments/assets/9adcfa24-031d-4aa2-8750-9a579406951b)

**Comment by stefano-lacorazza** [comment]
> Is the video ending when the person stops talking? Because if you watch it, the video ends much earlier than the indicated `end`
> 
>  2024-09-16.22-34-56.mp4

The ending cursor is currently paced where the last script ends. After https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/306#pullrequestreview-2306328146 is merged it will end at the last scene
