### ISSUE TITLE
FEAT: Sign Up flow

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#3]
### What feature?

- [x] Add name column to users table through migration
- [x] Update model
- [x] Update service to save user
- [x] Use encryption service to hash user password before saving to the db
- [x] Add /auth/sign-up endpoint to the controller
- [x] Return object with user property in response (exclude password_hash and password_salt columns)
- [x] Add validation (check with the dev who is implementing FE task)

**Comment by nikita-remeslov** [comment]
Check it please - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/4#issuecomment-2312608976

**Comment by DaniellaZambrano** [comment]
@JPjok3r How do you test the APIs on Swagger to make requests on the sign-up route?

**Comment by JPjok3r** [comment]
Hi @DaniellaZambrano this is needed to test from swagger, `{
    "fullName": "John Doe",
    "email": "email@gmail.com",
    "password": "string",
    "confirmPassword": "string"
}` this example data object structure should be sent to the endpoint for a successful store in database and receive `status: 200`, and for error the same as in FE.

**Comment by JPjok3r** [comment]
@DaniellaZambrano  well acording what we have, the url should be "http://localhost:3001/api/v1/auth/sign-up", and in the body is missing confirmPassword

**Comment by DaniellaZambrano** [comment]
@JPjok3r That’s how it is in Swagger; I’m not sure who added it that way, but those are the fields that are currently there. I can't add fields I’m not familiar with. If you check Swagger, you’ll see there isn’t more information available.

**Comment by JPjok3r** [comment]
@DaniellaZambrano  yes I was checking that, in sign-in is the same, who was in charge of that task, and here you can add fields, when you click on Try it out button and before clicking on execute 

![Image](https://github.com/user-attachments/assets/3c262118-03bc-4aab-a41d-1c800da8d9a5)

But anyway I saw the url is wrong, that is why you are getting `404 "not found"`

**Comment by DaniellaZambrano** [comment]
@JPjok3r can you give me the steps by steps to reproduce it?

**Comment by JPjok3r** [comment]
Yes sure @DaniellaZambrano :
1. Click on Try it out button

![Image](https://github.com/user-attachments/assets/1b42b742-0ddc-434b-a5eb-c4efa752af6b)

2. Click anywhere in the area where the data is printed


![Image](https://github.com/user-attachments/assets/0a37c0a3-a9c7-4846-894d-41affefbddb7)

3. Then click execute.
I saw Sanchousina is updating the documentation, but her Pull Request hasn't been merged yet, so maybe you will still getting 404.

**Comment by DaniellaZambrano** [comment]
@JPjok3r I'm not talking about that. I need is the URL you use and settings from localhost

**Comment by DaniellaZambrano** [comment]
Postman response:

![Image](https://github.com/user-attachments/assets/c1d16b82-6617-4f66-8216-b5800265fa24)
