### ISSUE TITLE
BUG: Generic Thumbnails Displayed Instead of Video Thumbnails

### ISSUE THREAD

**Issue by DaniellaZambrano** [BinaryStudioAcademy/bsa-2024-outreachvids#307]
### Describe your issue

When displaying the user's videos on the home page, the system generates and shows a generic placeholder thumbnail for each video. The thumbnails are not correctly representing the actual content of the uploaded videos.

### Steps to reproduce

1. Navigate to the home page as a logged-in user with uploaded videos.
2. Observe the video list/grid displaying the user's videos.
3. Check the thumbnail for each video in the list.

### What was the actual result?

All videos are shown with the same generic placeholder thumbnail instead of a video-specific thumbnail.

![Image](https://github.com/user-attachments/assets/1bb05d13-be41-4529-91db-46c03b559ebe)

### What was the expected result?

Each video should have a thumbnail that accurately represents a frame from the video itself 

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome, Safari, Edge, Firefox, Opera

### Severity

Minor (S4)

**Comment by stefano-lacorazza** [comment]
I dont think this is a bug, the unique image for each video feature is not implemented yet.

**Comment by lfelix3011** [comment]
This task will implement the frontend part of this other task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/298

**Comment by lfelix3011** [comment]
@DaniellaZambrano  The changes made here were also done in this PR https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/311, as that one was already merge, this one will be closed
