### ISSUE TITLE
FEAT: Add timeline component

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#31]
### What feature?

We will have a video editor in our application so the task is to develop a timeline of a video

Use https://www.npmjs.com/package/dnd-timeline

For now, mock the video length

The final product should have multiple layers of text in the timeline

Each layer should store info about text placement in the video, text value, and the time when it should appear in the video(You can mock this for now)

Useful links:
https://react-video-editor.netlify.app/
https://samuel-arbibe.gitbook.io/dnd-timeline

### Add screenshots

Example: 
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/57f8dbd6-33db-45f9-8438-8a35649dd223">

**Comment by stefano-lacorazza** [comment]
Hi! To the developer who is gonna review the timeline component you can replace app.tsx (LOCALLY) with the following code so it renders just the timeline component with mock items and rows for easy testing:


import { Timeline } from '../bundles/video_editor/components/timeline/timeline.js';
import { type ItemDefinition, type Range, type RowDefinition } from 'dnd-timeline';
import { generateMockRows, generateMockItems } from '~/bundles/video_editor/helpers/mock.helper.js';
import { minutesToMilliseconds } from 'date-fns';
const timezoneOffset = minutesToMilliseconds(new Date().getTimezoneOffset());
const initialRange: Range = {
    start: timezoneOffset,
    end: minutesToMilliseconds(45) + timezoneOffset,
};
const initialRows: RowDefinition[] = generateMockRows(15);
const initialItems: ItemDefinition[] = generateMockItems(10, initialRange, initialRows);
const App: React.FC = () => {
    return (
		<Timeline initialRange={initialRange} initialItems={initialItems} initialRows={initialRows} />
    );
};
export { App };


Any question or recommendation please tell me, im happy to help and learn.

**Comment by DaniellaZambrano** [comment]
Also I think in future that we can change the names of the each layer
