### ISSUE TITLE
BUG: Logo is not visible on white background

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#312]
### Describe your issue

Logo is not visible on white background

### Steps to reproduce

1. Go to studio page
2. Open AI Chat
3. Send message
4. Logo inside loader is not visible

### What was the actual result?

Logo is not visible on white background

### What was the expected result?

Logo is visible on white background

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/0426a0bd-9ac2-4aa3-9d16-06f6cbb6bf2a)
![Image](https://github.com/user-attachments/assets/01bcb334-6267-4de5-a4a9-9e0668f9ec37)

### What OS are you seeing the problem on?

MacOS, Windows, Android, iOS

### What browsers are you seeing the problem on?

Chrome, Safari, Edge, Firefox, Opera

### Severity

Major (S3)

**Comment by DaniellaZambrano** [comment]
Perfect 
![Image](https://github.com/user-attachments/assets/7d5ea046-7ccb-48b0-9d66-2456b4ef178e)
