### ISSUE TITLE
Rename CSS classes from camelCase to kebab-case

### ISSUE THREAD

**Issue by stefano-lacorazza** [BinaryStudioAcademy/bsa-2024-outreachvids#335]
Some styles.module.css files use camelCase for class names. To maintain consistency, we need to rename all CSS class names from camelCase to kebab-case.

Tasks:

- [ ] Identify all camelCase class names in the CSS files.
- [x] Rename each camelCase class name to kebab-case.
- [ ] Update all references to these class names in the corresponding .tsx files.

**Comment by DaniellaZambrano** [comment]
Missing 

/frontend/src/bundles/studio/components/video-menu/components/menu/menu.module.css
/frontend/src/bundles/common/components/video-modal/video-modal.module.css

**Comment by stefano-lacorazza** [comment]
> Missing
> 
> /frontend/src/bundles/studio/components/video-menu/components/menu/menu.module.css /frontend/src/bundles/common/components/video-modal/video-modal.module.css

Those files are not longer missing in next.
