### ISSUE TITLE
FEAT: Swagger API documentation

### ISSUE THREAD

**Issue by JKaypa** [BinaryStudioAcademy/bsa-2024-outreachvids#34]
### What feature?

- [x]  Update swagger 
- [x] Add sign-in swagger docs

**Comment by DaniellaZambrano** [comment]
Successful testing of a part of the FE functionality is complete, but full testing is blocked until the FEAT: Sign Up flow (BE) part is implemented

Attach FE ![Image](https://github.com/user-attachments/assets/0b0a7d40-156f-4596-9773-773a6d6db3b5)

**Comment by DaniellaZambrano** [comment]
Waiting for `FEAT: Sign Up flow (BE)` because what we currently have will change according to the requirements and what has already been completed for `FEAT: Sign Up flow (FE)`

![Image](https://github.com/user-attachments/assets/ae2edd9a-f4eb-4eec-b4de-4b611dbcaba3)

**Comment by DaniellaZambrano** [comment]
To test use last version on github of the branch "next" and follow the link
 [http://localhost:3001/v1/documentation/](http://localhost:3001/v1/documentation/)

**Comment by DaniellaZambrano** [comment]
@JKaypa The schema of `sign-up` changes, so I'll move this ticket to `In Progress` column for you to solve it.

**Comment by DaniellaZambrano** [comment]
Testing is done with the API implementation for now, and we've agreed that each new endpoint will be implemented swagger doc by the developer assigned to it.
