### ISSUE TITLE
FEAT: Add draft tag

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#350]
### What feature?

Add this draft tag as in the reference for videos that don't have a ready url

### Add screenshots

![Image](https://github.com/user-attachments/assets/cf89cdea-5500-4e71-b763-a2b126960359)

### Acceptance criteria

- [x] Videos, that were not completed and have no ready URL, should be marked with 'Draft' tag

### Testing documentation

https://docs.google.com/spreadsheets/d/1OXXcyv94vEVQeGB3AaYqgremUU7FLdrxkUV6bz03S0g/edit?gid=1927397104#gid=1927397104

**Comment by alien513** [comment]
The feature works as expected.

![Image](https://github.com/user-attachments/assets/ad913eae-6405-4d34-8d0c-1fc6623be10a)
