### ISSUE TITLE
FEAT: Delete draft video button

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#351]
### What feature?

Right now only rendered videos can be deleted. Make sure that the delete button is visible and working for draft videos as well

### Acceptance criteria

- [x] Video context menu should contain the 'Delete' option for drafts
- [x] Clicking the 'Delete' option should result in removing the draft video from the system

### Testing documentation

https://docs.google.com/spreadsheets/d/1OXXcyv94vEVQeGB3AaYqgremUU7FLdrxkUV6bz03S0g/edit?gid=1927397104#gid=1927397104

**Comment by Sanchousina** [comment]
Please attach pr

**Comment by alien513** [comment]
The feature works as expected.

![Image](https://github.com/user-attachments/assets/cc0d7248-aefa-465f-aa2d-6bddb1925dde)
