### ISSUE TITLE
TASK: Check voices after submit button click

### ISSUE THREAD

**Issue by Alblupynos** [BinaryStudioAcademy/bsa-2024-outreachvids#355]
### What task?

Check voices after the submit button click. Are they downloaded and duration set correctly? 

### Acceptance Criteria

- [x] When the submit button is clicked, the system should initiate the download process for the selected voice(s).
- [x] The duration of each downloaded voice should be set and displayed correctly.
- [ ] Provide visual feedback (e.g., a loading spinner or progress bar) during the downloading process, and confirmation once the download and duration setting are complete.
- [x] Verify that the voices are properly saved and playable, and the correct duration is associated with each one.
- [x] Ensure functionality works correctly across different browsers (Chrome, Firefox, Edge).
- [x] The submission and download process should not introduce significant delays

**Comment by DaniellaZambrano** [comment]
Duration of voices set correctly :D

![Image](https://github.com/user-attachments/assets/97e8063f-5330-43bd-869b-8e409ae318a1)
