### ISSUE TITLE
BUG: Script segments are longer than the voice causing pauses at the end of each segment

### ISSUE THREAD

**Issue by alien513** [BinaryStudioAcademy/bsa-2024-outreachvids#360]
### Describe your issue

On Studio page script segments are longer than the voice causing pauses at the end of each segment when the video plays.

### Steps to reproduce

1. Open the site: http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com.
2. Press 'Create video'.
3. Add 2 default script segments.
4. Add 1 scene.
5. Press the 'Play' button to play the video.
6. Observe how the video plays.

### What was the actual result?

Each segment has a long pause at the end.

### What was the expected result?

The next segment should start right after the previous one without pauses.

### Put here any screenshots or videos (optional)

Video: https://www.loom.com/share/0cd6563be1ed46c391d2f0a9abcdb654?sid=eb3ff6e9-fbe9-41ca-99b4-299a040306d1

### What OS are you seeing the problem on?

Windows 11

### What browsers are you seeing the problem on?

Firefox 129.0.2 (64x)
Chrome 128.0.6613.113 (x64)

### Severity

Major (S3)

**Comment by Alblupynos** [comment]
This issue is already fixed https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/372.

**Comment by alien513** [comment]
The bug was fixed.
