### ISSUE TITLE
FEAT: Fix remotion Bug

### ISSUE THREAD

**Issue by sergiy4** [BinaryStudioAcademy/bsa-2024-outreachvids#366]
### What feature?

You should fix remotion render Bug

### Acceptance criteria

- [x]  This should fix the Add remotion render ticket (https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/322)

### Testing documentation

No testing documentation (minor fix).

**Comment by alien513** [comment]
Remotion works as expected.
