### ISSUE TITLE
TASK: Create consent component

### ISSUE THREAD

**Issue by stefano-lacorazza** [BinaryStudioAcademy/bsa-2024-outreachvids#368]
### What Task?
Create Consent Component

#### Summary:
Develop a UI component that prompts the user to record a consent video, ensuring they confirm their identity and prevent misuse of the avatar creation technology. The "Record a Consent" button does not need to have any functionality at this stage.

#### Details:

1. **Prompt for Consent Video:**
   - Display a message prompting the user to record a consent video.

2. **Record a Consent Button:**
   - Add a "Record a Consent" button with a camera icon.
   - The button does not need to perform any action in this task.
 
3. **Generate Avatar Button:**
   - Add a "Generate Avatar Button" button bellow the concent box.
   - The button does not need to perform any action in this task.

![Image](https://github.com/user-attachments/assets/70ed6fcd-017e-4a0f-80a0-cdf68ae98899)

**Comment by DaniellaZambrano** [comment]
This version only implements the UI elements without functional behavior.
