### ISSUE TITLE
FEAT: Integrate AWS S3 and add file upload plugin

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#37]
### What feature?

Create FileService which would be used to upload images/videos to AWS S3 Bucket
Also create a plugin on the backend which would handle file uploading in the requests

Contact @nikita-remeslov to get the needed keys to AWS

**Comment by DaniellaZambrano** [comment]
@o-nedashkivska Thanks for this feature everything was ok!
