### ISSUE TITLE
FEAT: fix remotion bug

### ISSUE THREAD

**Issue by sergiy4** [BinaryStudioAcademy/bsa-2024-outreachvids#370]
### What feature?

fix remotion bug

### Acceptance criteria

- [x]  This should fix the Add remotion render ticket (https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/322)

### Testing documentation

No testing documentation (minor fix).

**Comment by alien513** [comment]
Remotion works as expected.
