### ISSUE TITLE
FEAT: Replace photo with video placeholder image

### ISSUE THREAD

**Issue by stefano-lacorazza** [BinaryStudioAcademy/bsa-2024-outreachvids#374]
### What feature?

Replace the file photo.png with some some abstract placeholder for videos in case of not loading or errors.

### Add screenshots

![Image](https://github.com/user-attachments/assets/b007f1e9-47df-4899-963a-abe6e3165243)

### Acceptance criteria

- [x] When a video is in the process of loading, the abstract placeholder should be shown until the video thumbnail successfully loads.
- [x] The placeholder should remain visible until the video thumbnail either loads successfully or remains if the video never loads.
- [x] Verify that the placeholder is displayed correctly in different scenarios (e.g., video loading, video error, etc.).
- [x] Check for responsiveness and cross-browser compatibility for desktop versions.

**Comment by Sanchousina** [comment]
Please attach pr
