### ISSUE TITLE
FEAT: Add Homepage

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#38]
### What feature?

Create a Homepage with a Video components

Mock the data for now

### Add screenshots

<img width="736" alt="image" src="https://github.com/user-attachments/assets/a580d127-e097-44e6-9a73-2b5bee514710">

**Comment by alien513** [comment]
Home page is located and displayed correctly.

![Image](https://github.com/user-attachments/assets/3fb2b9d0-5ec5-40de-b56b-96e55fbe746c)
