### ISSUE TITLE
FEAT: Integrate Open AI

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#39]
### What feature?

Create AI service on the backend to make requests to Open AI.
Use SDK for this.

We will use it in the chat so most likely model gpt-4o-mini would be enough for this

This service would be later used to create personal texts for video to a specific user based on user input in the chat so set restrictions to only generate text for a video.

**Comment by DaniellaZambrano** [comment]
Elena helped me with the AI part because requests to ChatGPT are banned in my country.

**Comment by alien513** [comment]
The component works correctly.

![Image](https://github.com/user-attachments/assets/48b1aaea-16b8-46a2-99eb-a1ed2c42459a)
