### ISSUE TITLE
FEAT: Add script component

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#41]
### What feature?

First part: Create script component and mock all the data
Second part: On OpenAI logo it should open some kind of a chat where we will talk to Open AI

Use this as example of chat https://www.heygen.com/

### Add screenshots

<img width="359" alt="image" src="https://github.com/user-attachments/assets/f0f28d21-5edf-41bb-a063-a99b3bb65857">

**Comment by o-nedashkivska** [comment]
Was splitted into three tasks: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/104, https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/144 and https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/166
