### ISSUE TITLE
FEAT: Add PWA

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#43]
### What feature?

Add PWA to our application

https://vite-pwa-org.netlify.app/

**Comment by DaniellaZambrano** [comment]
@WilsonBravo what is the part of code that you added this?

**Comment by WilsonBravo** [comment]
@DaniellaZambrano Mostly in vite.config file 

![Image](https://github.com/user-attachments/assets/5aecb449-0fc6-47cd-a3c0-c63733dcd5f3)

In plugins, all the VitePWA properties

![Image](https://github.com/user-attachments/assets/44e7f58e-f370-4f67-9efb-62525ed0de06)

**Comment by DaniellaZambrano** [comment]
Perfect thanks! :D
