### ISSUE TITLE
TASK: Create test documentation for Swagger API feature

### ISSUE THREAD

**Issue by DaniellaZambrano** [BinaryStudioAcademy/bsa-2024-outreachvids#46]
### What task?

- [x] A comprehensive list of test cases covering all Swagger API endpoints.
- [x] Each test case should include detailed steps, expected results, and criteria for passing.
- [x]  Ensuring that all API endpoints are thoroughly tested for functionality, reliability, and compliance with specifications

The link to the doc:
https://docs.google.com/document/d/1WCvmZwpYSouGX9Jji0Eu6JmsGEtEpxSeF12wAJmQxZs/edit?usp=sharing

**Comment by DaniellaZambrano** [comment]
Thanks Stefano :D Also you used the implemented [component](https://github.com/orgs/BinaryStudioAcademy/projects/30/views/1?filterQuery=is%3Aissue+assignee%3Asergiy4&pane=issue&itemId=75383600) perfect!

![Image](https://github.com/user-attachments/assets/a10b3679-37ce-4f8a-986a-bd715bc60953)

**Comment by alien513** [comment]
The document contains info about 3 endpoints, while there are already 13 of them. Should it be updated with new endpoints? And also maybe it would be better to add example values for request and response?

**Comment by DaniellaZambrano** [comment]
Those were the ones available at the time of creating the documentation hehe, that's why there are only 3 :D
