### ISSUE TITLE
FEAT: JWT token

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#5]
### What feature?

- [x]  Add token service to the backend with create and verify methods
- [x]  The token should store a user id
- [x]  The token should expire after 24h
- [x]  Return token in response to the sign-in and sign-up

Lib for JWT token - https://www.npmjs.com/package/jose

### Add screenshots

![image](https://github.com/user-attachments/assets/8135726b-487c-4802-8b24-b4b922b58cbf)

**Comment by stefano-lacorazza** [comment]
To implement 'Return token in response to the sign-in and sign-up' I merged OV-2-add-sign-in-flow to OV-5-JWT-token

**Comment by DaniellaZambrano** [comment]
Excellent! Thanks. Just a question, why id is in that format?

![Image](https://github.com/user-attachments/assets/56f66e1c-6a90-4a14-91b4-d51b2321c8e9)

**Comment by stefano-lacorazza** [comment]
> Excellent! Thanks. Just a question, why id is in that format?
> 
> ![Image](https://private-user-images.githubusercontent.com/36011797/363554738-56f66e1c-6a90-4a14-91b4-d51b2321c8e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzM0ODAsIm5iZiI6MTcyNTI3MzE4MCwicGF0aCI6Ii8zNjAxMTc5Ny8zNjM1NTQ3MzgtNTZmNjZlMWMtNmE5MC00YTE0LTkxYjQtZDUxYjIzMjFjOGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDRmZDc1MTQ0YTU4MTY4OThlNWMyODEwZDRhZjgwNmQ4YzM4YjA0MGRjZjFiNTk2MTFkNGI5NDYyZmZjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v9nL5ULSpKwZVOQlVhbEQlc8nw6s1KajLP44wH8oIxs)

The id is automatically created by the database when the user is created by user.repository
