### ISSUE TITLE
FEAT: Add getCurrentUser endpoint

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#51]
### What feature?

Your task is to implement getting current user by the token.

This token we will store in localStorage after we obtain it from the backend.

You should create a request to the server where you will obtain the user by the id stored in the token, return it to the client, and store it in the redux store.

If the JWT task or sign-in/sign-up tasks are not in next branch yet just merge them into yours

**Comment by DaniellaZambrano** [comment]
@Alblupynos can you give please the complete route of the endpoint?
I didn't find on the code

**Comment by Alblupynos** [comment]
Yes, sure, write you in slack

**Comment by DaniellaZambrano** [comment]
Thanks for the link, works perfect your endpoint
![Image](https://github.com/user-attachments/assets/26abcc8f-7032-40e7-a005-f8d0b37ba8b1)

**Comment by DaniellaZambrano** [comment]
Thanks for the link, works perfect your endpoint

![Image](https://github.com/user-attachments/assets/51140804-1efd-4690-96d4-ce513f15bff5)
