### ISSUE TITLE
FEAT: Add video API

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#59]
### What feature?

Create a table in database where we would store info about user videos. It should contain id, userId, name of the video, url, createdAt and updatedAt

Also create controller, service and repo to implement crud operations

**Comment by DaniellaZambrano** [comment]
Good, thanks!
![Image](https://github.com/user-attachments/assets/afe3eca4-da0c-46f3-a38d-c094f8801193)

**Comment by DaniellaZambrano** [comment]
Good, thanks!
![Image](https://github.com/user-attachments/assets/3879967a-57be-4d93-a48b-1e2647cd9858)
