### ISSUE TITLE
FEAT: Loader component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#6]
### What feature?

- [x] Create Loader common component
- [x] Loader should use our logo
- [x] Create Loader Overlay component using Loader component

P.S. For design use out project design

**Comment by DaniellaZambrano** [comment]
The loader is fine, it just needs the logo added once the image is ready

![Image](https://github.com/user-attachments/assets/3c13f70d-2e18-410d-8d48-7e7e6a99d2bf)

**Comment by DaniellaZambrano** [comment]
Acceptance criteria passed!
