### ISSUE TITLE
FEAT: Add files API

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#60]
### What feature?

Create a table where we would store info about files.

it should contain id, url, type(video or photo), createdAt, updatedAt

Url is the link from AWS S3 Bucket

When we upload the file to AWS we should store the link to it in files table so also create a service + repository for it

Merge the AWS S3 into your branch if it is not in the next branch yet.

**Comment by o-nedashkivska** [comment]
Please add support for audio files with extension `.wav` and for video with extension `webm`. And before creating pull request test locally if script audio is loaded without any errors.

**Comment by DaniellaZambrano** [comment]
fine
![Image](https://github.com/user-attachments/assets/af4824bc-1800-4a2e-ad20-08e64e974d7e)
