### ISSUE TITLE
FEAT:  Add Create avatar page

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2024-outreachvids#62]
### What feature?

For now just simply add layout with button

### Add screenshots

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5ea51840-1cb6-4ba3-9d2c-0f5d379d3e87">

**Comment by o-nedashkivska** [comment]
Please, close this ticket because connected pr has 0 changes

**Comment by alien513** [comment]
'My avatar' page was added.

![Image](https://github.com/user-attachments/assets/26636550-2296-466c-bdc5-8d2209f57bbb)
