### ISSUE TITLE
TASK: Sign in flow (frontend) testing documentation

### ISSUE THREAD

**Issue by alien513** [BinaryStudioAcademy/bsa-2024-outreachvids#65]
### What task?

- [x] Create User Stories
- [ ] Create a Check List
- [x] Create Test Cases

### Testing documentation

https://docs.google.com/spreadsheets/d/18qkQs1BYpclGpN9TGDBwBefp4q7TLVE2cnlwckDCbiI/edit?gid=1927397104#gid=1927397104

**Comment by alien513** [comment]
https://docs.google.com/spreadsheets/d/1d63JvjfgyAzlrIXHnvQGVjHTIcl8GKXZ/edit?gid=1922746335#gid=1922746335

**Comment by DaniellaZambrano** [comment]
Translating it (sorry, my Google interface is in Spanish) means that the link you gave me is currently in the trash, visible for now, but will soon be deleted completely

![Image](https://github.com/user-attachments/assets/4f28d45d-09c5-43ea-ba42-3cc15654d253)

**Comment by alien513** [comment]
Please check this one: https://docs.google.com/spreadsheets/d/18qkQs1BYpclGpN9TGDBwBefp4q7TLVE2cnlwckDCbiI/edit?gid=1927397104#gid=1927397104

**Comment by DaniellaZambrano** [comment]
Perfect! Update the link in the top of description :)
