### ISSUE TITLE
FEAT: Error handling

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#7]
### What feature?

- [x] Implement error-handling middleware in the redux store
- [x] When an error occurs, show a toast notification

Doc: https://v2.chakra-ui.com/docs/components/toast/usage#standalone-toasts

P.S. For toast use out design styles

### Acceptance criteria

- [x] The middleware should accurately detect errors
- [x] When an error occurs, a toast notification should be displayed to the user
- [ ] Error message should be clear and concise, shouldn't contain unnecessary technical details and should be displayed in English
- [x] The site should continue to function, as much as possible, even in the presence of errors (avoid site crashing or freezing when an error occurs)

### Testing documentation

https://docs.google.com/spreadsheets/d/1Dn7B49WQK0oi5bE3dmx_Ay1TH0Y1p3QUNDn3VvKWH0o/edit?gid=1927397104#gid=1927397104

**Comment by alien513** [comment]
The component works correctly.

![Image](https://github.com/user-attachments/assets/798d48f8-f1c8-448e-8c6a-80958b652af9)

![Image](https://github.com/user-attachments/assets/20c37432-1ddf-4a77-8d60-a90aa296a919)

**Comment by alien513** [comment]
Created a bug: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/184
