### ISSUE TITLE
FEAT: Add 'Generate script with AI' tab to video modal

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#73]
### What feature?

Add 'Generate script with AI' tab to video modal.

### Add screenshots

Reference (from https://heygen.com/):

<img width="1566" alt="Screenshot 2024-08-27 at 20 10 46" src="https://github.com/user-attachments/assets/7fad861c-1610-4409-a0a4-f69cdb0a70f4">

Reference must be used as a template, the exact styles must correspond to the existing app design.

Right now only 'Topic Input' section should be implemented.

**Comment by alien513** [comment]
This component can't be found on the page for now. Pending.

**Comment by alien513** [comment]
Great, thank you! Marking as completed.

![Image](https://github.com/user-attachments/assets/fd35a05c-5b6a-4db3-af74-9f1ac5dab9f4)
