### ISSUE TITLE
FEAT: Add sidebar and header to Home page

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#75]
### What feature?

Integrate sidebar and header to the home page as shown on the design

### Add screenshots

![Image](https://github.com/user-attachments/assets/243d5eb1-cbc6-4782-93c4-88a68ba78217)

**Comment by stefano-lacorazza** [comment]
Hi, sorry but isnt the header component already implemented?

![Image](https://github.com/user-attachments/assets/86c19c01-09f5-45a0-8523-2a811d16f04c)

**Comment by stefano-lacorazza** [comment]
Ok done. 

![Image](https://github.com/user-attachments/assets/4d2a110c-917c-4654-b6f9-03fe4bdadc80)
