### ISSUE TITLE
TASK: Fix swagger docs

### ISSUE THREAD

**Issue by Sanchousina** [BinaryStudioAcademy/bsa-2024-outreachvids#77]
### What task?

Fix current swagger documentation for auth and user controllers

**Comment by DaniellaZambrano** [comment]
Hi @Sanchousina can you give me please the exactly route for this? Because I got this message:

![Image](https://github.com/user-attachments/assets/0d513f7d-19a0-4b4c-a679-ae2fdd50ee6e)

**Comment by Sanchousina** [comment]
> Hi [@Sanchousina](https://github.com/Sanchousina) can you give me please the exactly route for this? Because I got this message:
> 
> ![Image](https://github.com/user-attachments/assets/0d513f7d-19a0-4b4c-a679-ae2fdd50ee6e)

Hi! The fix for this is in OV-95, it is not merged yet

**Comment by DaniellaZambrano** [comment]
Thank you!! :D

![Image](https://github.com/user-attachments/assets/2ddeea81-dc08-42ec-b974-b1a292f9dc30)
