### ISSUE TITLE
Make Page responsive with default brekpoints

### ISSUE THREAD

**Issue by lfelix3011** [BinaryStudioAcademy/bsa-2024-outreachvids#87]
The folowing page sould be responsive in all default breakpints
- [x] Sign-In
- [x] Sign-Up
- [x] Studio

**Comment by DaniellaZambrano** [comment]
It works! Thank you


![Image](https://github.com/user-attachments/assets/9136c0d5-ba57-4e09-bc47-cdfe06e32ba9)
![Image](https://github.com/user-attachments/assets/faafb1e2-ee53-4c93-ac51-ffff289f7934)
![Image](https://github.com/user-attachments/assets/b77ddb64-ea4f-4735-85ca-2b2784ce83c2)
