### ISSUE TITLE
FEAT: Protect Routing

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#9]
### What feature?

- [x] Create ProtectedRoute component
- [x] Redirect unauthorized users from protected pages to the Sign In page

**Comment by alien513** [comment]
This component does not perform any actions yet and allows access to all routes until user persistence is implemented. Pending.

**Comment by alien513** [comment]
Bugs created: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/210, https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/213
Bugs should be resolved in the following fix: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/187

Pending.
